### ISSUE TITLE
Private Network ip

### ISSUE THREAD

**Issue by iamjoshellis** [amwill04/vagrant-python#2]
Should a specific private ip be committed to source?
In `vagrantfile`, line 3:
`config.vm.network :private_network, ip: "192.168.33.10"`
While valid, could cause issues on certain networks.
Would it not be better to commit the following to source?
`config.vm.network "private_network", type: "dhcp"`
As this will work on all networks with dhcp enabled, then add static ip config instructions to `README.md`

**Comment by amwill04** [comment]
most boxes seem to come with the 192.168.33.10 ip address setting as default so seem pertinent to use it myself.
